- src/main/java/com/globalnest/be/alarm/domain/Alarm.java
- src/main/java/com/globalnest/be/alarm/repository/AlarmRepository.java
- src/main/java/com/globalnest/be/comment/domain/Comment.java
- src/main/java/com/globalnest/be/comment/repository/CommentRepository.java
- src/main/java/com/globalnest/be/post/domain/Post.java
- src/main/java/com/globalnest/be/post/domain/PostImage.java
- src/main/java/com/globalnest/be/post/domain/PostLike.java
- src/main/java/com/globalnest/be/post/domain/PostTag.java
- src/main/java/com/globalnest/be/post/domain/type/Tag.java
- src/main/java/com/globalnest/be/post/repository/PostImageRepository.java
- src/main/java/com/globalnest/be/post/repository/PostLikeRepository.java
- src/main/java/com/globalnest/be/post/repository/PostRepository.java
- src/main/java/com/globalnest/be/post/repository/PostTagRepository.java
- src/main/java/com/globalnest/be/user/domain/Subscribe.java
- Resolves #
> 엔티티 설정 및 repository 생성
- 엔티티 설정 및 repository 생성
> feat: 엔티티 설정 및 repository 생성

- src/main/java/com/globalnest/be/translation/dto/Choice.java
- src/main/java/com/globalnest/be/translation/dto/Comment.java
- src/main/java/com/globalnest/be/translation/dto/Message.java
- src/main/java/com/globalnest/be/translation/dto/request/ChatRequest.java
- src/main/java/com/globalnest/be/translation/dto/response/ChatResponse.java
- src/main/java/com/globalnest/be/translation/util/TranslationClient.java
> feat : GPT 요청을 위한 기본 정보 추가

- src/main/java/com/globalnest/be/oauth/dto/CustomOAuth2User.java
- src/main/java/com/globalnest/be/oauth/service/CustomOAuth2UserService.java
- src/main/java/com/globalnest/be/oauth/util/AuthenticationUtil.java
- src/main/java/com/globalnest/be/user/domain/User.java
- src/main/java/com/globalnest/be/user/dto/request/FirstLoginRequest.java
- src/main/java/com/globalnest/be/user/service/UserService.java
- OAuthUser 구성에 name 추가 및 nickname 분리
- 유저 인증 객체에도 name 추가
- Resolves #
> 00
- 00
> feat : 사용자 정보에 이름 추가

- src/main/java/com/globalnest/be/petition/domain/Agreement.java
- src/main/java/com/globalnest/be/petition/domain/Petition.java
- src/main/java/com/globalnest/be/petition/domain/type/PetitionType.java
- src/main/java/com/globalnest/be/petition/repository/AgreementRepository.java
- src/main/java/com/globalnest/be/petition/repository/PetitionRepository.java
- Petition 추가
- Agreement 추가
- Resolves #
> 00
- 00
> feat : 청원 관련 엔티티 추가

- src/main/java/com/globalnest/be/oauth/controller/AuthController.java
- src/main/java/com/globalnest/be/post/dto/response/PostResponse.java
- src/main/java/com/globalnest/be/post/presentation/PostController.java
- Resolves #
> 게시글 조회 부분 미비 사항 추가 구현
- 게시글 조회 부분 미비 사항 추가 구현
> feat: 게시글 조회 부분 미비 사항 추가 구현

- src/main/java/com/globalnest/be/oauth/dto/CustomOAuth2User.java
- src/main/java/com/globalnest/be/oauth/service/CustomOAuth2UserService.java
- src/main/java/com/globalnest/be/oauth/util/AuthenticationUtil.java
- src/main/java/com/globalnest/be/user/domain/User.java
> feat : 인증 객체에 언어 및 직종 추가

- src/main/java/com/globalnest/be/comment/dto/response/CommentResponse.java
- src/main/java/com/globalnest/be/comment/repository/CommentRepository.java
- src/main/java/com/globalnest/be/comment/repository/CommentRepositoryCustom.java
- src/main/java/com/globalnest/be/comment/repository/CommentRepositoryImpl.java
- src/main/java/com/globalnest/be/post/application/PostService.java
- src/main/java/com/globalnest/be/post/domain/Post.java
- src/main/java/com/globalnest/be/post/dto/response/PostDetailResponse.java
- src/main/java/com/globalnest/be/post/dto/response/PostRepoResponse.java
- src/main/java/com/globalnest/be/post/dto/response/PostResponse.java
- src/main/java/com/globalnest/be/post/presentation/PostController.java
- src/main/java/com/globalnest/be/post/repository/PostRepositoryCustom.java
- src/main/java/com/globalnest/be/post/repository/PostRepositoryImpl.java
- src/main/java/com/globalnest/be/post/repository/PostTagRepository.java
- src/main/java/com/globalnest/be/post/repository/dto/PostRepoResponse.java
- src/main/java/com/globalnest/be/post/repository/init/PostInitializer.java
- src/main/java/com/globalnest/be/post/repository/init/PostLikeInitializer.java
- src/main/java/com/globalnest/be/post/repository/init/PostTagInitializer.java
- Resolves #
> 게시글 상세 조회 구현
- 게시글 상세 조회 구현
> feat: 게시글 상세 조회 구현

- src/main/java/com/globalnest/be/comment/application/CommentService.java
- src/main/java/com/globalnest/be/comment/dto/response/CommentResponseList.java
- src/main/java/com/globalnest/be/comment/presentation/CommentController.java
- src/main/java/com/globalnest/be/post/presentation/PostController.java
- Resolves #
> 댓글 추가 조회 기능 구현
- 댓글 추가 조회 기능 구현
> feat: 댓글 추가 조회 기능 구현

- src/main/java/com/globalnest/be/post/application/PostService.java
- src/main/java/com/globalnest/be/post/dto/request/PostUploadRequest.java
- src/main/java/com/globalnest/be/post/presentation/PostController.java
- src/main/java/com/globalnest/be/user/service/UserService.java
- Resolves #
> 게시글 업로드 구현
- 게시글 업로드 구현
> feat: 게시글 업로드 구현

- src/main/java/com/globalnest/be/post/application/PostService.java
- src/main/java/com/globalnest/be/post/domain/type/Tag.java
- Resolves #
> 게시글 업로드 태그 저장 구현
- 게시글 업로드 태그 저장 구현
> feat: 게시글 업로드 태그 저장 구현

- src/main/java/com/globalnest/be/petition/application/PetitionService.java
- src/main/java/com/globalnest/be/petition/presentation/PetitionController.java
> feat : 잘못된 import 제거

- src/main/java/com/globalnest/be/petition/application/PetitionService.java
- src/main/java/com/globalnest/be/petition/domain/type/PetitionType.java
- src/main/java/com/globalnest/be/petition/dto/request/PetitionUploadRequest.java
- src/main/java/com/globalnest/be/petition/dto/response/PetitionDetailResponse.java
- src/main/java/com/globalnest/be/petition/dto/response/PetitionResponse.java
- src/main/java/com/globalnest/be/petition/exception/AgreementDuplicateException.java
- src/main/java/com/globalnest/be/petition/exception/PetitionNotFoundException.java
- src/main/java/com/globalnest/be/petition/exception/errorcode/AgreementErrorCode.java
- src/main/java/com/globalnest/be/petition/exception/errorcode/PetitionErrorCode.java
- src/main/java/com/globalnest/be/petition/presentation/PetitionController.java
- src/main/java/com/globalnest/be/petition/repository/AgreementRepository.java
- src/main/java/com/globalnest/be/petition/repository/PetitionRepositoryCustom.java
- src/main/java/com/globalnest/be/petition/repository/PetitionRepositoryImpl.java
- src/main/java/com/globalnest/be/petition/repository/init/PetitionInitializer.java
> feat : 청원 상세 페이지 조회 및 서명 로직

- src/main/java/com/globalnest/be/post/dto/response/PostResponse.java
- src/main/java/com/globalnest/be/post/repository/PostRepositoryImpl.java
- src/main/java/com/globalnest/be/post/repository/dto/PostRepoResponse.java
- Resolves #
> 게시글 조회 제목 누락 수정
- 게시글 조회 제목 누락 수정
> fix: 게시글 조회 제목 누락 수정

- src/main/java/com/globalnest/be/comment/dto/response/CommentResponse.java
- src/main/java/com/globalnest/be/post/dto/response/PostResponse.java
- Resolves #
> 시간 출력 형식 변경
- 시간 출력 형식 변경
> fix: 시간 출력 형식 변경

- src/main/java/com/globalnest/be/post/application/PostService.java
- src/main/java/com/globalnest/be/post/presentation/PostController.java
- src/main/java/com/globalnest/be/post/repository/PostRepositoryCustom.java
- src/main/java/com/globalnest/be/post/repository/PostRepositoryImpl.java
- src/main/java/com/globalnest/be/user/repository/init/UserInitializer.java
- Resolves #
> 필터링 기능 구현
- 필터링 기능 구현
> feat: 필터링 기능 구현

- src/main/java/com/globalnest/be/petition/dto/request/PetitionUploadRequest.java
> fix : 청원 날짜 업로드 방식 변경

- src/main/java/com/globalnest/be/post/repository/init/PostInitializer.java
- Resolves #
> 더미 데이터 추가
- 더미 데이터 추가
> feat: 더미 데이터 추가

- src/main/java/com/globalnest/be/post/dto/response/PostResponseList.java
- Resolves #
> 게시글 조회에 part 추가
- 게시글 조회에 part 추가
> feat: 게시글 조회에 part 추가

- src/main/java/com/globalnest/be/oauth/util/jwt/JwtTokenProvider.java
- src/main/java/com/globalnest/be/petition/presentation/PetitionController.java
> fix : SameSite None으로 변경

- src/main/java/com/globalnest/be/user/repository/init/UserInitializer.java
- Resolves #
> 추천 유저 더미 데이터 추가
- 추천 유저 더미 데이터 추가
> feat: 추천 유저 더미 데이터 추가

- src/main/java/com/globalnest/be/comment/presentation/CommentController.java
- src/main/java/com/globalnest/be/oauth/util/jwt/JwtTokenProvider.java
- src/main/java/com/globalnest/be/petition/application/PetitionService.java
- src/main/java/com/globalnest/be/petition/dto/response/PetitionResponseList.java
- src/main/java/com/globalnest/be/petition/presentation/PetitionController.java
- src/main/java/com/globalnest/be/petition/repository/PetitionRepositoryCustom.java
- src/main/java/com/globalnest/be/petition/repository/PetitionRepositoryImpl.java
- src/main/java/com/globalnest/be/post/presentation/PostController.java
- src/main/java/com/globalnest/be/user/presentation/UserController.java
> fix : 청원 리스트 로직 변경 및 응답 구조 변경

- src/main/java/com/globalnest/be/comment/presentation/CommentController.java
- src/main/java/com/globalnest/be/global/util/translation/TranslationConverter.java
- src/main/java/com/globalnest/be/global/util/translation/client/TranslationClient.java
- src/main/java/com/globalnest/be/global/util/translation/dto/Choice.java
- src/main/java/com/globalnest/be/global/util/translation/dto/Message.java
- src/main/java/com/globalnest/be/global/util/translation/dto/request/ChatRequest.java
- src/main/java/com/globalnest/be/global/util/translation/dto/response/ChatResponse.java
- src/main/java/com/globalnest/be/petition/presentation/PetitionController.java
- src/main/java/com/globalnest/be/post/presentation/PostController.java
- src/main/java/com/globalnest/be/user/presentation/UserController.java
> feat : 번역 전체 적용

- src/main/java/com/globalnest/be/petition/dto/response/PetitionDetailResponse.java
> fix : 변수명 오탈자 수정

- src/main/java/com/globalnest/be/petition/repository/init/PetitionInitializer.java
> feat : 더미 데이터 추가

- src/main/java/com/globalnest/be/user/domain/User.java
- src/main/java/com/globalnest/be/user/repository/init/UserInitializer.java
> feat : user 더미 데이터 갱신

- src/main/java/com/globalnest/be/oauth/controller/AuthController.java
- src/main/java/com/globalnest/be/oauth/service/AuthService.java
> fix : 리프레쉬 로직 변경

- src/main/java/com/globalnest/be/oauth/controller/AuthController.java
> feat: 헤더 변경

- src/main/java/com/globalnest/be/oauth/controller/AuthController.java
> fix : 헤더변경

- src/main/java/com/globalnest/be/oauth/controller/AuthController.java
> fix :refresh 로직 변경
